-- MySQL Script generated by MySQL Workbench
-- Wed Sep 12 23:49:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema misperris
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `misperris` ;

-- -----------------------------------------------------
-- Schema misperris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `misperris` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `misperris` ;

-- -----------------------------------------------------
-- Table `ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciudad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ciudad` (
  `IdCiudad` INT(11) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `region_IdRegion` INT(11) NOT NULL,
  PRIMARY KEY (`IdCiudad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `Correo` VARCHAR(45) NOT NULL,
  `RutCliente` VARCHAR(45) NOT NULL,
  `NombreCompleto` VARCHAR(45) NOT NULL,
  `FechaNaci` DATE NOT NULL,
  `Telefono` INT(11) NOT NULL,
  `TipoVivienda` VARCHAR(45) NOT NULL,
  `region_IdRegion` INT(11) NOT NULL,
  `ciudad_IdCiudad` INT(11) NOT NULL,
  PRIMARY KEY (`RutCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `login` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `login` (
  `User` VARCHAR(45) NOT NULL,
  `Pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `region` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `region` (
  `IdRegion` INT(11) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdRegion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
